version: "3.7"
services:
   eureka:
     image: ulisesgs/eureka
     ports:
       - "8761:8761"
     restart: always
     networks:
       - spring
   servicio_mysql:
      image: mysql:8
      ports:
        - "3307:3306"
      restart: always
      networks:
        - spring
      environment:
        MYSQL_DATABASE: db_biblioteca
        MYSQL_ROOT_PASSWORD: root
   autor_postgresql:
     image: postgres:latest
     ports:
       - "5432:5432"
     restart: always
     networks:
       - spring
     environment:
       POSTGRES_DB: msvc_biblioteca
       POSTGRES_PASSWORD: root

   msvc-autor:
     image: autor:latest
     restart: always
     ports:

       - "8002:8002"
     networks:
       - spring
     depends_on:
       - eureka
       - autor_postgresql
   msvc-libro:
     image: libro:latest
     restart: always
     ports:

       - "8001:8001"
     networks:
       - spring
     depends_on:
       - eureka
       - servicio_mysql

   msvc-gateway:
     image: ulisesgs/gateway:latest
     restart: always
     ports:
       - "8090:8090"
     networks:
       - spring
     depends_on:
       - eureka
       - msvc-autor
       - msvc-libro


networks:
  spring: